const Projects = [
  {
    id: 10,
    name: "Zero Waste",
    description: "A Web application of anti waste of food products.",
    photo: "img/projects/ZeroWaste.png",
    album: [
      { photo: "img/projects/ZeroWaste1.png" },
      { photo: "img/projects/ZeroWaste2.png" },
      { photo: "img/projects/ZeroWaste3.png" },
      { photo: "img/projects/ZeroWaste4.png" },
      { photo: "img/projects/ZeroWaste5.png" },
    ],
    url: "",
    urlbool: false,
    accesweb: "",
    description2:
      "Designing and Realizing a Web application of anti waste of food products.",
    Functional: [
      "User Management",
      "Product Management",
      "Basket Management",
      "Ordering Management",
      "Reclamation Management",
      "Recipe Management",
      "Trash Management",
    ],
    Tags: [
      "ReactJS, Redux, NodeJs, ExpressJs, MongoDB, Python, Git, Github, Scrum, Trello",
    ],
    company: "ESPRIT",
    start: "01/01/2023",
    end: "01/05/2023",
  },
  {
    id: 1,
    name: "Commercial Web Application",
    description:
      "A professional commercial web application that aims to help people look for all kind of products.",
    photo: "img/projects/3aweni3.png",
    album: [{ photo: "img/projects/angular.png" }],
    description2:
      "Realizing a professional commercial web application that aims to help people look for all kind of products.",
    Functional: [
      "Product Management",
      "Comment Management",
      "Basket Management",
      "Ordering Management",
      "User Management",
    ],
    url: "Website",
    urlbool: true,
    accesweb: "https://3aweni.netlify.app/",
    Tags: ["Angular, Spring, MySql, Git"],
    company: "ESPRIT",
    start: "15/09/2022",
    end: "15/10/2022",
  },
  {
    id: 9,
    name: "Desktop Application",
    description:
      "A professional desktop Appliaction that aims to help managing a university dormitory.",
    photo: "img/projects/timesheet.png",
    album: [{ photo: "img/projects/glade.png" }],
    description2: [
      "Realizing a professional desktop Appliaction that aims to help managing a university dormitory.",
    ],
    Functional: [],
    url: "Git Link",
    urlbool: true,
    accesweb: "https://github.com/Samar-web-prog/Devops",
    Tags: ["Ubuntu(Linux), C Language, Glade"],
    company: "Esprit",
    start: "20/09/2021",
    end: "20/11/2021",
  },
  {
    id: 11,
    name: "Microservices Project",
    description: "Microservices project",
    photo: "img/projects/microservice.png",
    album: [
      { photo: "img/projects/11/photo1.png" },
      { photo: "img/projects/11/photo2.png" },
      { photo: "img/projects/11/photo3.png" },
      { photo: "img/projects/11/photo4.png" },
    ],
    description2: [
      "Develop micro-services with spring boot and nodejs",
      "BDs are: H2, mysql and mongoDB",
      "The Gateway (Proxy) for the configuration of micro-service routes.",
      "Deploy microservices on containers",
      "Ensure the security of the microservices architecture.",
    ],
    Functional: [],
    url: "Git Link",
    urlbool: true,
    accesweb: "https://github.com/siwarhassen/microservice",
    Tags: [
      "Angular, Springboot, NodeJs, ExpressJS, MySQL, H2, Microservices, Github",
    ],
    company: "Esprit",
    start: "2021.09.02",
    end: "2021.11.27",
  },
  {
    id: 2,
    name: "BricoFast (ux design)",
    description:
      "Learn the basics of web product development through the design thinking process.",
    photo: "img/projects/brico.png",
    album: [
      { photo: "img/projects/2/photo1.png" },
      { photo: "img/projects/2/photo2.png" },
      { photo: "img/projects/2/photo3.png" },
      { photo: "img/projects/2/photo4.png" },
      { photo: "img/projects/2/photo5.png" },
      { photo: "img/projects/2/photo6.png" },
      { photo: "img/projects/2/photo7.png" },
      { photo: "img/projects/2/photo8.png" },
    ],
    Functional: [],
    url: "",
    urlbool: false,
    accesweb: "",
    Tags: ["Figma, Adobe Photoshop, Consider Ly, UX Design"],
    company: "Esprit",
    start: "2021.09.02",
    end: "2021.11.29",
  },
  {
    id: 8,
    name: "Preclinic",
    description:
      "A platform that makes it easier for Proxym employees to request appointments online with doctors",
    photo: "img/projects/preclinic.png",
    album: [
      { photo: "img/projects/8/photo1.png" },
      { photo: "img/projects/8/photo2.png" },
      { photo: "img/projects/8/photo3.png" },
      { photo: "img/projects/8/photo4.png" },
      { photo: "img/projects/8/photo5.png" },
      { photo: "img/projects/8/photo6.png" },
      { photo: "img/projects/8/photo7.png" },
      { photo: "img/projects/8/photo8.png" },
      { photo: "img/projects/8/photo9.png" },
      { photo: "img/projects/8/photo10.png" },
      { photo: "img/projects/8/photo11.png" },
      { photo: "img/projects/8/photo12.png" },
      { photo: "img/projects/8/photo13.png" },
    ],
    description2:
      "During this internship, I was asked to design and develop a platform that facilitates the Proxym staff’s request for online appointments with doctors who are agreed with the company.",
    Functional: [
      "Consult the list of doctors",
      "Check the status of appointments",
      "View appointment history",
      "Cancel an appointment",
      "Make an appointment",
      "Find a doctor",
      "Manage appointments(doctors part)",
      "Manage work schedule",
      "Manage availability",
      "View Notifications",
    ],
    url: "Git Link",
    urlbool: false,
    accesweb: "",
    Tags: [
      "Angular NX, Ngrx, NestJS,MySQL, Workspace NX,Github, Bitbucket, Microservices ",
    ],
    company: "Proxym IT",
    start: "2021.07.11",
    end: "2021.09.11",
  },
  {
    id: 6,
    name: "VideDressing",
    description:
      "Online wardrobe sale where people can buy, sell or trade new or used fashion items.",
    photo: "img/projects/videdressing.png",
    album: [
      { photo: "img/projects/6/photo1.png" },
      { photo: "img/projects/6/photo2.png" },
      { photo: "img/projects/6/photo3.png" },
      { photo: "img/projects/6/photo4.png" },
      { photo: "img/projects/6/photo5.png" },
      { photo: "img/projects/6/photo6.png" },
      { photo: "img/projects/6/photo7.png" },
      { photo: "img/projects/6/photo8.png" },
      { photo: "img/projects/6/photo9.png" },
      { photo: "img/projects/6/photo10.png" },
      { photo: "img/projects/6/photo11.png" },
      { photo: "img/projects/6/photo12.png" },
    ],
    description2:
      " A social fashion network whose goal is simple: allow people to renew their wardrobe by selling their unused clothes and to buy others at low prices.",
    Functional: ["Product management", "Order management", "Caddy management "],
    url: "Git Link",
    urlbool: true,
    accesweb: "https://github.com/siwarhassen/projetAngular",
    Tags: ["Angular, SpringBoot, Github, MySQL"],
    company: "",
    start: "2020.11.01",
    end: "2020.12.31",
  },
  {
    id: 7,
    name: "HVAC",
    description:
      "HVAC is a web application that offers to help users sell or buy a car.",
    photo: "img/projects/hvac.png",
    album: [
      { photo: "img/projects/7/photo1.png" },
      { photo: "img/projects/7/photo2.png" },
      { photo: "img/projects/7/photo3.png" },
      { photo: "img/projects/7/photo4.png" },
    ],
    description2:
      "This application offers a wide selection of vehicles and allows you to sort by brand, model, MPG, price, etc. You will see the initial prices and no haggling, so that you know what you will pay in advance. Users can also sell their cars",
    Functional: ["Car management", "Comment management", "Manage favorites"],
    url: "Git Link",
    urlbool: true,
    accesweb: "https://github.com/siwarhassen/automobile",
    Tags: ["Angular, Ngrx, NodeJS,Mongodb, SEM,Git"],
    company: "Proxym IT",
    start: "2020.07.09",
    end: "2020.09.09",
  },
  {
    id: 3,
    name: "Tunisian Got Talent",
    description:
      "Is a Multiplatform application: (web, desktop and mobile), dedicated for the talented.",
    photo: "img/projects/tunisian.png",
    album: [
      { photo: "img/projects/3/photo5.png" },
      { photo: "img/projects/3/photo1.png" },
      { photo: "img/projects/3/photo2.png" },
      { photo: "img/projects/3/photo3.png" },
      { photo: "img/projects/3/photo4.png" },
      { photo: "img/projects/3/photo6.png" },
    ],
    description2:
      "Tunisia’s got talent is a multiplatform application: (web ,desktop and mobile), dedicated to talented  . This application is carried out as part of an integrated project in group of 5 people. As the development of this Application is carried out in group, We have shared the tasks between us. So I was responsible for user management and the management of videos published by users.",
    Functional: [
      "Post management",
      "Course management",
      "Event management",
      "Video and film management",
      "Product management",
      "Recruitment management",
    ],
    url: "",
    urlbool: false,
    accesweb: "",
    Tags: ["PHP, Symfony,Java,JavaFX, codenameone"],
    company: "Esprit",
    start: "2020",
    end: "2020",
  },
  {
    id: 5,
    name: "Design cuisine",
    description:
      "A web application that was created in collaboration with a furniture sales company.",
    photo: "img/projects/designcuisine.png",
    album: [
      { photo: "img/projects/5/photo1.png" },
      { photo: "img/projects/5/photo2.png" },
      { photo: "img/projects/5/photo3.png" },
      { photo: "img/projects/5/photo4.png" },
    ],
    description2:
      "This project is carried out by 6 people for 5 months. It was for a real customer who expressed a desire to create a website in order to present his activities and products and create a direct link with his customers. An attractive, dynamic and interactive website, both for its administration and for its use, is then necessary for the proper functioning and internal and external communication of such a structure.",
    Functional: [
      "User and contact management",
      "Product management",
      "Order management",
      "Employee management",
      "Delivery management",
      "After-sales service management",
    ],
    url: "",
    urlbool: false,
    accesweb: "",
    Tags: ["HTML,CSS ,Oracle"],
    company: "Esprit",
    start: "2019",
    end: "2019",
  },
  {
    id: 4,
    name: "Smarket",
    description:
      "Smarket allows the user to manage a supermarket in an easier way.",
    photo: "img/projects/smarket.png",
    album: [
      { photo: "img/projects/4/photo1.png" },
      { photo: "img/projects/4/photo2.png" },
      { photo: "img/projects/4/photo3.png" },
      { photo: "img/projects/4/photo4.png" },
      { photo: "img/projects/4/photo5.png" },
    ],
    description2:
      "Smarket is an application that allows the user to manage a supermarket in an easier way. This application consists of an application for stock management, trolley management, cash management, safety management and parking management.",
    Functional: [
      "Product management",
      "Trolley management",
      "Shelf management",
      "Order management",
      "Employee management",
      "Supplier management",
    ],
    url: "",
    urlbool: false,
    accesweb: "",
    Tags: ["Api Qt, c++, Oracle, Arduino"],
    company: "Esprit",
    start: "2018",
    end: "2018",
  },
];

export default Projects;
